turbine:
  #参数指定了需要收集监控信息的服务名，多个使用逗号隔开
  appConfig: feign-client
  #参数指定了集群名称为 default，当我们服务数量非常多的时候，可以启动多个 Turbine 服务来构建不同的聚合集群，而该参数可以用来区分这些不同的聚合集群，同时该参数值可以在 Hystrix 仪表盘中用来定位不同的聚合集群，只需要在 Hystrix Stream 的 URL 中通过 cluster 参数来指定；
  clusterNameExpression: "'default'"
  #可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以 host 来区分不同的服务，这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计
  combineHostPort: true
  #如果被监控的服务中设置了context-path,需要在Turbine中指定turbine.instanceUrlSuffix来解决
  instanceUrlSuffix: ${info.actuator-prefix}/hystrix.stream

management:
  endpoints:
    web:
      base-path: /${info.actuator-prefix}       #修改前缀，默认是/actuator
      path-mapping:
        health: ${info.health-check-url}  #修改健康检查路由
      exposure:
        include: "*"         #暴露所有端点 默认是info,health
    endpoint:
      health:
        show-details: ALWAYS

spring:
  boot:
    admin:
      ui:
        # 修改网页显示的tab标题
        title: "Linitly-应用监控平台"
        # 修改网页的brand的图标和标题
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>Linitly-应用监控平台</span>"

logging:
  config: classpath:log/logback-spring.xml
  level:
    com.siwei.life.insurance.dao: debug
  file: ./log-${spring.application.name}/${spring.application.name}.log
