spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linitly_springcloud?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

foo:
  foo: feign-test-2

management:
  endpoints:
    web:
      base-path: /${info.actuator-prefix}       #修改前缀，默认是/actuator
      path-mapping:
        health: ${info.health-check-url}  #修改健康检查路由
      exposure:
        include: "*"         #暴露所有端点 默认是info,health
    endpoint:
      health:
        show-details: ALWAYS

ribbon:
  #http建立socket超时时间，单位毫秒
  ConnectTimeout: 1000
  #http读取响应socket超时时间
  ReadTimeout: 3000
  #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetries: 0
  #重试负载均衡其他的实例最大重试次数,不包括首次server
  MaxAutoRetriesNextServer: 1
  #是否所有操作都重试，默认只有get请求重试，post等接口如果没有幂等性设计，且开启重试后果严重
#  OkToRetryOnAllOperations: true

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 9000        #断路器超时时间，默认1000ms

logging:
  config: classpath:log/logback-spring.xml
  level:
    com.linitly.feign.client.dao: debug
  file: ./log-${spring.application.name}/${spring.application.name}.log

springfox:
  documentation:
    swagger:
      v2:
        path: /v${info.version}/v2/api-docs          #修改swagger的请求路径，默认为/v2/api-docs