spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linitly_springcloud?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

foo:
  foo: test1

management:
  endpoints:
    web:
      base-path: /actu       #修改前缀，默认是/actuator
      path-mapping:
        health: healthcheck  #修改健康检查路由
      exposure:
        include: "*"         #暴露所有端点 默认是info,health